### ISSUE TITLE
Example doesn't work!

### ISSUE THREAD

**Issue by micahscopes** [brysgo/graphql-gun#21] opened 2017-12-31 09:02 UTC
I copy-pasted the example from `README.md` into a project with gun 0.9.5 and graphql 0.12.3... I get:

```
index.js:24 Uncaught TypeError: Cannot read property 'live' of null
    at resolver (index.js:24)
    at executeField (graphql.js:86)
    at graphql.js:36
    at Array.map (<anonymous>)
    at executeSelectionSet (graphql.js:31)
    at graphql (graphql.js:25)
    at graphqlGun (index.js:87)
    at Object../src/index.jsx (index.jsx:43)
    at __webpack_require__ (bootstrap c4b2e4a17cfdd9fb5807:678)
    at fn (bootstrap c4b2e4a17cfdd9fb5807:88)
resolver @ index.js:24
executeField @ graphql.js:86
(anonymous) @ graphql.js:36
executeSelectionSet @ graphql.js:31
graphql @ graphql.js:25
graphqlGun @ index.js:87
./src/index.jsx @ index.jsx:43
__webpack_require__ @ bootstrap c4b2e4a17cfdd9fb5807:678
fn @ bootstrap c4b2e4a17cfdd9fb5807:88
0 @ index.jsx:94
__webpack_require__ @ bootstrap c4b2e4a17cfdd9fb5807:678
(anonymous) @ bootstrap c4b2e4a17cfdd9fb5807:724
(anonymous) @ bootstrap c4b2e4a17cfdd9fb5807:724
```

**Comment by brysgo** [comment] 2017-12-31 15:02
Thanks for reporting this, I will take a look at the example again. Can you try cloning and running the tests / do they pass?

**Comment by micahscopes** [comment] 2017-12-31 21:02
No problem! When I upgrade gun to 0.9.5 in the dependencies, I get 5 failures and 7 successes

**Comment by micahscopes** [comment] 2017-12-31 21:05
actually... I get the same failures with gun 0.8.9

**Comment by micahscopes** [comment] 2017-12-31 21:07
Okay, changing to gun 0.8.0 gives only 2 failures and 10 passing

**Comment by micahscopes** [comment] 2017-12-31 21:19
looks like the failures pop up between gun 0.8.7 and 0.8.8

**Comment by brysgo** [comment] 2017-12-31 22:26
Thanks, I'm on a ski vacation. But I'll try to get to it ASAP.

**Comment by micahscopes** [comment] 2018-01-01 01:04
Oh take yer time I'm in no rush... I might even be able to fix it this week
when I get back behind the desk again

**Comment by amark** [comment] 2018-03-08 11:00
people keep asking about GraphQL + GUN, and I know this was working at some point. What is the status? This could be huge! :)

**Comment by brysgo** [comment] 2018-03-08 15:56
I don't have a ton of time for this but I'm happy to onboard a new maintainer if someone is willing.

**Comment by micahscopes** [comment] 2018-03-08 20:17
@amark I've been focused on making ends meet, but I do plan on using GUN in an pending project.  hopefully I'll have time to dig into this. 

If you can trace back to see what happened between 0.8.7 and 0.8.9, maybe it wouldn't be too hard to fix the problem?  Unfortunately, NPM doesn't associate versions with git revisions, so it was hard for me to get any more specific.

**Comment by brysgo** [comment] 2018-03-28 03:19
@amark - I think the biggest problem is with sets not working anymore.

Can you tell me if a change in gundb would have broken this: https://github.com/brysgo/graphql-gun/blob/master/index.js#L59

**Comment by amark** [comment] 2018-03-30 06:41
@brysgo that looks right...

What is the error message?

**Comment by brysgo** [comment] 2018-04-02 01:20
I updated everything, ran the tests, and it looks like once graphql gun gets into a set, everything inside the set is just empty objects.

**Comment by to-jajav33** [comment] 2018-04-15 05:39
not sure if this might be related... but there is some info in the change log about .set() being deprecated. I changed mine to .put() in another project. Here is the changelog that says it changed.

https://github.com/amark/gun/blob/master/CHANGELOG.md#03

**Comment by brysgo** [comment] 2018-04-15 22:09
That could be it, we use set in a couple of the tests, it isn't used in the implementation though.

**Comment by brysgo** [comment] 2018-07-01 15:32
Reason I never fixed this is when I went to fix it, a host of other bugs showed up. This is fixed here: https://github.com/brysgo/graphql-gun/pull/23

There are still failing tests that are caused by overloading the call stack. I will investigate those next.

**Comment by amark** [comment] 2018-07-01 15:49
Yay progress!!!!!

Could you post the stack trace error?

Is it coming from GUN?

**Comment by brysgo** [comment] 2018-07-01 16:35
I don't have reason to believe that it is from GUN

**Comment by brysgo** [comment] 2018-07-01 17:05
Stack trace is here:
https://circleci.com/gh/brysgo/graphql-gun/121

```
    RangeError: Maximum call stack size exceeded
        at Array.forEach (native)

      at merge (node_modules/graphql-anywhere/src/graphql.ts:283:21)
      at node_modules/graphql-anywhere/src/graphql.ts:285:7
      at Array.forEach (native)
      at merge (node_modules/graphql-anywhere/src/graphql.ts:283:21)
      at node_modules/graphql-anywhere/src/graphql.ts:285:7
      at Array.forEach (native)
```

I think the error is here:
https://github.com/brysgo/graphql-anywhere/blob/npm/src/graphql.ts#L283

**Comment by brysgo** [comment] 2018-07-01 17:07
Seems like there is a circular object in the result that is breaking it.

**Comment by amark** [comment] 2018-07-01 18:12
The way I handle that with circular graph data I gun that I return to users is I keep a table of "seen" IDs/souls and then use that as a check to stop recursion. (I also usually have the seen table store the JS reference to the object so I can reuse that object.)

**Comment by brysgo** [comment] 2018-07-05 20:54
@micahscopes this should be fixed, please re-open if you are still having trouble!

**Comment by amark** [comment] 2018-07-05 20:55
w000h00! Things are getting back to being awesome :D :D :D

**Closed by brysgo** 2018-07-05 20:54 UTC
Labels: help wanted
